# Generated by Django 5.1.2 on 2024-10-23 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='ZpdN7fGHnqZ8sZWlLah1H8ERZugciqJm', editable=False, max_length=32, unique=True),
        ),
    ]
