# Generated by Django 5.1.2 on 2024-10-23 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0002_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='ubj81ThrkbSsBCV2i6DstCvbpvUcJlK4', editable=False, max_length=32, unique=True),
        ),
    ]
